# Generated by Django 3.2.3 on 2024-02-24 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_options_follow'),
        ('recipes', '0002_initial'),
    ]

    operations = [
    ]
