# Generated by Django 3.2.3 on 2024-03-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_ingredient_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeTag',
        ),
    ]
