# Generated by Django 3.2.3 on 2024-03-07 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(code='wrong_hex_code', message='Неверный формат цвета.', regex='^#[a-fA-F0-9]{6}$')], verbose_name='Цвет'),
        ),
    ]
