# Generated by Django 3.2.3 on 2024-03-07 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время меньше 1 недопустимо.'), django.core.validators.MaxValueValidator(32000, message='Время больше 32000 недопустимо.')], verbose_name='Время приготовления, мин.'),
        ),
    ]
