# Generated by Django 3.2.3 on 2024-03-09 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Введите код цвета в формате hex (#ABCDEF)', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(code='wrong_hex_code', message='Неверный формат цвета.', regex='^#[A-F0-9]{6}$')], verbose_name='Цвет'),
        ),
    ]
