# Generated by Django 4.2.6 on 2023-11-19 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='No_self_subscription',
        ),
    ]
