# Generated by Django 3.2.3 on 2024-03-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240227_2150'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='cannt follow themselves',
        ),
    ]
