# Generated by Django 3.2.3 on 2024-03-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_follow_cannt follow themselves'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='cannt follow themselves',
        ),
    ]
