# Generated by Django 3.2.3 on 2024-03-05 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240305_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('[^&&][^^][^*][^|][^"]', 'Запрещенные символы.')], verbose_name='Логин'),
        ),
    ]
